### ISSUE TITLE
pip3 install cec failed

### ISSUE THREAD

**Issue by tomtom2401** [stg93/blaulichtsms_einsatzmonitor_tv_controller#1]
ich hab das pip3 package cec installiert, jedoch meint der installer, dass das package fehlt.
```
sudo ./INSTALL
Checking apt dependencies...
All apt dependencies are met

Checking pip dependencies...
Please install missing pip packages via
        'pip3 install cec'
```
somit ist keine installation aus des skript hreaus möglich. Habe über die direkten kommandos das cec getestet (echo 'on 0' | cec-client RPI -s -d 1) - funktioniert und somit sollte die installation auch durch sein.

**Comment by stg93** [comment]
Pip3 installiert die Module unter Debian standardmäßig nur für den User, welcher den Befehl ausführt. Da das INSTALL Skript für Systemd mit sudo ausgeführt wird, kann dieses nicht die Module importieren. Der Code enthält jetzt einen Fix welcher die Installation der pip3 Packete für alle User (`pip3 install --system pyyaml cec`) vorschlägt. Der User welcher den Befehl ausführt muss dafür in der Gruppe *staff* sein. `sudo adduser <username> staff` fügt den User zu der Gruppe hinzu.

**Comment by tomtom2401** [comment]
funktioniert nun (Y)
