### ISSUE TITLE
Problem mit Alarmzeit

### ISSUE THREAD

**Issue by godi1996** [stg93/blaulichtsms_einsatzmonitor_tv_controller#12]
Servus

Im file blaulichtsmscontroller.py in dem Codeabschnitt in welcher die Alamierungszeit abgefragt wird gibt es ein Problem.

Bei mir ist die Alamierungs-Uhrzeit um 1 Stunde im Rückstand deshalb funktioniert das automatische einschalten des TVs nicht 

denke das hier irgendwo der Fehler begraben sein könnte 

          alarm_datetime = datetime.strptime(
                alarm["alarmDate"],
                '%Y-%m-%dT%H:%M:%S.%fZ'

hoffe Sie können das Problem beheben.

Danke im voraus

**Comment by stg93** [comment]
Danke für die Meldung. Ich kenne das Problem und es gibt dafür auch schon Issue #9.

Ich werde nächste Woche einen Fix dafür veröffentlichen.
