### ISSUE TITLE
Fehler bei Installation - libcec4-dev missing

### ISSUE THREAD

**Issue by tomtom2401** [stg93/blaulichtsms_einsatzmonitor_tv_controller#15]
Beim Installieren der Pakete tritt bei libcec4-dev der Fehler auf, dass das Paket nicht gefunden werden kann.

Raspberry Model 3 B mit raspbian Buster

**Comment by StefanZettl** [comment]
Hi tomtom2401, 
nachdem wir auch BlaulichtSMS eingeführt, habe durch Zufall dieses Projekt hier gefunden. Habe das ganze auf einem Raspberry Pi 2 mit Raspian Buster installiert und an der selben Stelle hängen geblieben wie du. 

Ich hab das ganze mit folgenden Schritten zum laufen bekommen:

1. Installation libcec-dev 
`sudo apt install libcec-dev`
2. Editieren von INSTALL-Skript im Root-Ordner
`sudo nano INSTALL`

Hier musst du die Klammer hinter **requiredAptDependencies** anpassen so dass dort folgendes steht:
```
# Check dependencies
requiredAptDependencies=( "cec-utils" "libcec-dev" )
missingAptDependencies=()
```

Bei uns hat es gestern beim testen super funktioniert :)

**Comment by r00tat** [comment]
Hi, ist mit PR #21 behoeben!

**Comment by stg93** [comment]
@r00tat danke für das Beheben des Fehlers
