### ISSUE TITLE
Feature: Session in URL für Anmeldung mitgeben

### ISSUE THREAD

**Issue by tomtom2401** [stg93/blaulichtsms_einsatzmonitor_tv_controller#2]
**Ist deine Idee verwandt zu einem Problem?**
Chromium vergisst manchmal das Passwort.

**Beschreibe die Lösung die du dir vorstellst**
Man kann der URL des Dashboards über den token parameter die sessionId mitgeben. somit kann man das (einmalige) Anmelden in Chromium übergehen. Weiters ist somit eine sichere Anmeldung gegeben, sollte das Passwort mal "vergessen" werden.

**Zusätzliches**
siehe: [Einsatzmonitor Autologin](https://github.com/blaulichtSMS/docs/blob/master/dashboard_api_v1.md#einsatzmonitor-autologin)

Ich hatte das in der ersten Version des Einsatzmonitor TV Controllers so adaptiert:
`
content = {"username": USERNAME, "password": PASSWORD, "customerId": CUSTOMER_ID}
response = requests.post(BASE_URL + "login", json = content)
os.system("chromium-browser --noerrdialogs --incognito --start-fullscreen https://dashboard.blaulichtsms.net/#/login?token="+response.json()["sessionId"]+" --disable-translate &")
`

LG

**Comment by stg93** [comment]
Danke für den Hinweis. Ich habe schon nach einer Lösung für ein automatisches Login gesucht hatte aber bisher nichts gefunden.

Das Feature ist ab Version [v2.1](https://github.com/stg93/blaulichtsms_einsatzmonitor_tv_controller/releases/tag/v2.1) enthalten.
