### ISSUE TITLE
Chromium startet nicht in Vollbild

### ISSUE THREAD

**Issue by tomtom2401** [stg93/blaulichtsms_einsatzmonitor_tv_controller#3]
Chromium startet mit eingeblendeter Menüleiste (ca. 1/5 des Bildschirms hoch) und nicht Vollbild beim Aufruf des test.py skripts.

(weitere Idee bezüglich Chrome Autlogin siehe #2 )

**Comment by stg93** [comment]
Bisher hatte ich noch keine eingeblendete Menüleiste. Mir ist allerdings aufgefallen, dass wen Chromium bereits vor dem Start durch die Applikation am Laufen ist, dann funktioniert das Starten im Vollbild nicht.

**Comment by tomtom2401** [comment]
Ich werd das weiter beobachten und dann Rückmeldung geben - vielleicht fällt mir noch was auf

LG
