### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by noxish** [stg93/blaulichtsms_einsatzmonitor_tv_controller#4]
Servus :) 
Nettes Projekt 👍 

nur eine Frage hat sich für mich aufgetan
sollte Raspbian Stretch Minimal oder Desktop verwendet werden?

**Comment by stg93** [comment]
Danke! 

Für die Anzeige des Einsatzmonitors ist eine grafische Oberfläche erfoderlich. Daher ist Raspbian Stretch Desktop die richtige Wahl.

**Comment by noxish** [comment]
Pull Request gesendet 👍 #5
