### ISSUE TITLE
Eigener Infoscreen nach einer gewissen Zeit ohne Alarm

### ISSUE THREAD

**Issue by Rohrleitner** [stg93/blaulichtsms_einsatzmonitor_tv_controller#7]
Hallo stg93. Ich verfolge schon einige Zeit deine Bemühungen und bin sehr begeistert von deiner Lösung. Ich habe schon vor einigen Monaten begonnen auf Basis deines damals vorhanden Scripts einige Erweiterung einzubauen. Erstens habe ich die Möglichkeit hinzugefügt, dass nach einer gewissen Zeit statt dem Einsatzbildschirm eine andere Internetseite angezeigt wird auf der ich einen "Infoscreen" mit eigenen Informationen, laufende Einsätze im Bereich, Interner FF Kalender und Wettervorhersagen erstellt habe. Außerdem habe ich die Abschaltfunktion um eine Bewegungserkennung erweitert. D.h. wenn ein am Raspberry PI angeschlossener Bewegungsmelder eine Bewegung erkennt, schaltet er den Monitor aktiv und wenn nach einer vorgegebenen Zeit keine Bewegung erkannt wurde geht der Monitor wieder in Standby. Hier habe ich mehrere Zeiten berücksichtigt. Eine Zeit nach einem Alarm bei der der Monitor unbedingt aktiv bleibt, nach dieser Zeit wechselt der Bildschirm von Einsatzmonitor auf den Infomonitor und da, nach aktuell 3 Minuten, wenn keine Bewegung vor dem Schirm ist dann in den Standby-Modus des TV'S. Da ich glaube, dass diese Funktionalität auch für andere interessant wäre, stellt sich die Frage, ob wir hier nicht vielleicht gemeinsam was machen könnten. Es würde mich freuen wenn du mich kontaktieren würdest meine Nummer ist 066*******LG Charly @stg93

**Comment by stg93** [comment]
Hallo Charly,

entschuldige bitte die verspätete Antwort. Es freut mich sehr das jemand eine mögliche Erweiterungen denkt und diese auch umsetzt! Ich möchte allerdings mit diesem Repo nur den "Core" bereitstellen.

Da ich deine Arbeit sehr interessant finde und es sicher auch anderen so geht, würde ich mich freuen, wenn du einen Fork meines Repos erstellst und dort deine Erweiterungen zur Verfügung stellst.

Solltest du Fragen bei der Integration deiner Erweiterungen haben kannst du mir gerne eine Email schreiben: n05416077@feuerwehr.gv.at

LG
