### ISSUE TITLE
bitte um Hilfe bei der Installation

### ISSUE THREAD

**Issue by Chrisdor1** [stg93/blaulichtsms_einsatzmonitor_tv_controller#8]
hallo, 
bin gerade dabei mir das Programmieren beizubringen und bräuchte ein bisschen Hilfe!
Ich habe alle erforderlichen Bibliotheken installiert und den user zur gruppe staff hinzugefügt.
Ich muss jetzt noch die Konfiguration vor der Installation durchführen, soweit habe ich es verstanden.
Aber bezüglich des Source Code komme ich nicht weiter. Wo finde ich den und in welches Verzeichnis muss ich den vor der Installation verschieben?

LG Christoph

**Comment by noxish** [comment]
das Git Repository hast du ja heruntergeladen und das ist der Source Code :-) bzw. den Release unter 
https://github.com/stg93/blaulichtsms_einsatzmonitor_tv_controller/releases

**Comment by Chrisdor1** [comment]
Noch nicht, habe lediglich die angegebenen Bibliotheken am Raspberry installiert und dachte das ist das Git Repository.
Muss ich das Repository gleich mit dem Raspberry herunterladen oder mit dem Pc und dann die Daten auf den Raspberry übertragen? 

Sorry fals meine Fragen blöd sind, kenn mich aber damit noch nicht aus.

**Comment by noxish** [comment]
hiermit sollte es klappen denke ich "ohne es probiert zu haben"
1. `wget https://github.com/stg93/blaulichtsms_einsatzmonitor_tv_controller/archive/v2.1.1.tar.gz`
2. `tar xvfz v2.1.1.tar.gz`
3. `mv v2.1.1 blaulichtcontroller`
4. `cd blaulichtcontroller`
5. `python3 configure.py`
6. `sudo ./INSTALL`

und dann gehts eh hier weiter :) https://github.com/stg93/blaulichtsms_einsatzmonitor_tv_controller#verwendung

**Comment by Chrisdor1** [comment]
Danke, habe es gestern noch geschafft alles zu installieren und es funktioniert alles. Test Skript funktionierte auch ohne fehler.

Eine Frage hätte ich noch. Kann ich nach der Installation die Minuten die der Bildschirm eingeschaltet ist noch ändern? Wenn ja wo?

**Comment by stg93** [comment]
Nach der Konfiguration gibt es eine Konfigurationsdatei, **config.ini**. In dieser kann man mit der Variable **hdmi_cec_device_on_time** die Dauer in Sekunden einstellen.
